package sjsu.se137.team3.spartansurveys;


import android.content.Intent;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;
import android.support.v4.app.FragmentManager;
import android.support.v4.app.FragmentTransaction;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.TextView;

import org.w3c.dom.Text;

import java.util.ArrayList;


/**
 * Auto generated by new>Blank Fragment.
 * A simple {@link Fragment} subclass.
 * Created by Krystle on 5/11/2016
 * See surveylistfragment for adapter credit.
 */
public class MySurveyFragment extends Fragment {
    private RecyclerView surveyRecyclerView;
    private SurveyAdapter surveyAdapter;
    private Survey s;
    private ArrayList<Survey> mSurveyList = new ArrayList<>();
    //blank constructor
    public MySurveyFragment(){}

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        // Inflate view and make the recycler
        View layout = inflater.inflate(R.layout.fragment_survey_list, container, false);
        surveyRecyclerView = (RecyclerView) layout.findViewById(R.id.survey_recycler_view);
        surveyRecyclerView.setLayoutManager( new LinearLayoutManager(getActivity()) );
        //get info from the database, fill in the survey list to the adapter so the recycler view can be filled
        DatabaseManager dbm = new DatabaseManager();
        int userid = MyProperties.getInstance().userId;
        mSurveyList = dbm.getAllUserSurveys(userid);

        //set title of action bar
        getActivity().setTitle("My Surveys");
        surveyAdapter = new SurveyAdapter(mSurveyList);

        surveyRecyclerView.setAdapter(surveyAdapter);
        return layout;
    }

    @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);


    }

    private class SurveyHolder extends RecyclerView.ViewHolder implements View.OnClickListener {

        Survey surv;
        Bundle bundle = new Bundle();

        private Button surveyNameButton;

        public SurveyHolder(View itemView) {
            super(itemView);

            // Initialize name of survey inside SurveyHolder

            surveyNameButton = (Button) itemView.findViewById(R.id.survey_list_button);
            surveyNameButton.setOnClickListener(this);
        }

        // Bind survey to the holder and set name accordingly
        public void bindSurvey(Survey survey) {
            //pss the object to the main activity so the individual survey can be pulled
            surv = survey;
//            bundle.putParcelable("survey",surv);
            //this is the title of the survey in the button. click it and a response opens.
            surveyNameButton.setText(surv.getmTitle());
            surveyNameButton.setContentDescription(surv.getmDescription());
        }


        @Override
        public void onClick(View v) {
            switch (v.getId()) {
                case R.id.survey_list_button:
                    if(surv!=null){
                        bundle.putParcelable("survey",surv);
                    }
                   /* //try this
                    v.setTag(1,);
                    Intent intent = new Intent();
                    //pass in survey info to the next place
                    intent.putExtra(MainActivity.SURVEYNAME,surveyNameButton.getText().toString());
                    startActivity(intent);*/
                    //what to put here
                    Fragment frag = new ResponseListFragment();
                    FragmentManager fm = getFragmentManager();
                    frag.setArguments(bundle);
                    FragmentTransaction ft = fm.beginTransaction();
                   /* Bundle bundle = new Bundle();
                    bundle.putParcelable("Survey",s);
                    frag.setArguments(bundle);*/
                    ft.replace(R.id.fragment_container,frag);
//                    ft.replace(R.id.fragment_container, frag, "Survey Response");
                    ft.commit();
                    break;
            }
           /* Intent intent = new Intent();
            //pass in survey info to the next place
            intent.putExtra(MainActivity.SURVEYNAME,surveyNameButton.getText().toString());
            startActivity(intent);*/
        }
    }


    private class SurveyAdapter extends RecyclerView.Adapter<SurveyHolder> {
        private ArrayList<Survey> mList;
        //fill in the list
        public SurveyAdapter(ArrayList<Survey> list) {
            mList = list;
        }

        @Override
        public SurveyHolder onCreateViewHolder(ViewGroup parent, int viewType) {
            // Create the LayoutInflater that is used to inflate the SurveyList
            LayoutInflater layoutInflater = LayoutInflater.from(parent.getContext());

            View view = layoutInflater.inflate(R.layout.survey_list_item, parent, false);
            return new SurveyHolder(view);
        }

        @Override
        public void onBindViewHolder(SurveyHolder holder, int position) {
            // Get each survey in list and bind to holder
            Survey survey = mList.get(position);

//            getView().setTag(position,survey);
            holder.bindSurvey(survey);
        }

        @Override
        public int getItemCount() {
            return mSurveyList.size();
        }
    }
    //keeps our menu
    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setHasOptionsMenu(true);
    }

}